### ISSUE TITLE
Support Adding self to BIG-IQ as a managed device

### ISSUE THREAD

**Issue by f5-applebaum** [F5Networks/f5-declarative-onboarding#191]
### Is your feature request related to a problem? Please describe.

As a user, similar to defining BIG-IQ I would like to obtain a license from, ex.
https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/big-iq-licensing.html?highlight=bigiq

```
       myPoolLicense:
          class: License
          licenseType: licensePool
          bigIqHost: X.X.X.X
          bigIqUsername: mybigIQLicenseUser
          bigIqPassword: "{{{BIGIQ_PASSWORD}}}"
          licensePool: myUtilityPool1
          skuKeyword1: F5-BIG-MSP-BT-1G-IPI
          skuKeyword2: 
          unitOfMeasure: yearly
          tenant: mytenant1
          reachable: false
          overwrite: false
          hypervisor: aws
```

I would like to define the BIG-IQ I add as a managed device. 

Ideally has similar API/UX as Ansible Module.
https://docs.ansible.com/ansible/latest/collections/f5networks/f5_modules/bigiq_device_discovery_module.html
 
ex. something like this:
```
        myDns:
          class: DNS
          nameServers:
          - 8.8.8.8
        myBIGIQImport:
          class: BIGIQImport
          bigIqHost: '192.168.1.4'
          bigIqUsername: myImportUser
          bigIqPassword: "{{{BIGIQ_PASSWORD}}}"
          modules:
            - ltm
            - asm
          conflict_policy: use_bigip
        myNtp:
          class: NTP
          servers:
          - 0.pool.ntp.org
          timezone: UTC
```
