### ISSUE TITLE
Class User: Preserve SSH Authorized Keys for Cloud VE use cases

### ISSUE THREAD

**Issue by f5-applebaum** [F5Networks/f5-declarative-onboarding#193]
### Is your feature request related to a problem? Please describe.

When deploying a BIG-IP VE in cloud, the common practice to assign/associate the SSH key(s) with the instance. 

ex.
https://github.com/f5devcentral/terraform-aws-bigip/blob/master/variables.tf#L31
 
NOTE: In GCP, the agent actually updates the authorized keys to all the users in the project continuously. 

In cloud, the root account is disabled and **admin** is the default account.  However, DO only allows you to preserve the SSH key with the root account.

From:
https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/declarations/auth.html#adding-public-ssh-keys-to-a-declaration

"Only the root user’s primary key (noted by the Host Processor Superuser), in authorized_keys will be preserved"

### Describe the solution you'd like

As a user in cloud, I would like to set the password but preserve the SSH keys installed by the cloud. 

Desired Behavior:

      Common:
        class: Tenant
        admin:
            class: User
            userType: regular
            password: "{{{ ADMIN_PASS }}}"
            shell: bash        
        mySystem:
          class: System
          hostname: "{{ HOST_NAME }}"

Current Behavior.

User's authorized keys are wiped out. A cloud user could be accidentally be locked out of the instance (via any SSH automation) if only sends the Admin's *password* field and not "keys" field. 

Desired Behavior:

Add "preserveAuthKeys: true"  param to not wipe out existing cloud keys.

```
        class: Tenant
        admin:
            class: User
            userType: regular
            password: "{{{ ADMIN_PASS }}}"
            shell: bash  
            preserveAuthKeys: true
```

Declarative to achieve current behavior of wiping out keys 
```
        class: Tenant
        admin:
            class: User
            userType: regular
            password: "{{{ ADMIN_PASS }}}"
            shell: bash
           keys: []
```

To be declarative and overwrite any existing keys.
```
        class: Tenant
        admin:
            class: User
            userType: regular
            password: "{{{ ADMIN_PASS }}}"
            shell: bash
            keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCwHJLJY+/U/ioAAAADAQABAAACAQCwHJLJY+z0Rb85in7Ean6JS2J9dzo1nSssm7ZyQvGgc1e7EVtztbVpHThsvw92+1hx9wlSogXN6Co5zrtqlN8/mvlQkRRQ+sp2To8PcSMeEVI+TqBOg6BWbwwNQLz9/eUJq2o4vBfSpsn7GSDIf6C3F9EahRPGCR/z0kw5GZob3Q==
                test2
            - ssh-rsa AAAAB3NzaC1yc2EAu2Gr14xRiVLnG8KxNp2fO1/U/ioAz0Rb85in7Ean6JS2J9dzo1nSssm7ZyQvGgc1e7EVtztbVpHThsvw92+/mvlQkRRQ+sp2To8PcSMeEVI+TqBOg6BWbwwNQLzu2Gr14xRiVLnG8KxNp2fO19/eUJq2o4vBfSpsn7GSDIf6C3F9EahRPGCR/z0kw5GZob3Q==
                test
```
      
### Describe alternatives you've considered

You can provide the public key string via DO but it is more common workflow is to assign to the instance (via instance API ) at deploy time. 

### Additional Comments:

Originally was going to request applying the same behavior as root to admin, however, this wouldn't work for GCP as the primary key isn't sufficient as very common for the authorized keys to be a list (containing various project's users). Hence "preserveAuthKeys"  would be more robust solution.

**Comment by dstokesf5** [comment]
Thank you for your feedback. This has been added to our internal product backlog as AUTOTOOL-2465.

**Comment by dstokesf5** [comment]
@f5-applebaum, what behavior do you expect if preserveAuthKeys is used on a declaration update?

For example, if a user POSTs:
```
        class: Tenant
        admin:
            class: User
            userType: regular
            password: "{{{ ADMIN_PASS }}}"
            shell: bash
            keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCwHJLJY+/U/ioAAAADAQABAAACAQCwHJLJY+z0Rb85in7Ean6JS2J9dzo1nSssm7ZyQvGgc1e7EVtztbVpHThsvw92+1hx9wlSogXN6Co5zrtqlN8/mvlQkRRQ+sp2To8PcSMeEVI+TqBOg6BWbwwNQLz9/eUJq2o4vBfSpsn7GSDIf6C3F9EahRPGCR/z0kw5GZob3Q==
                test2
            - ssh-rsa AAAAB3NzaC1yc2EAu2Gr14xRiVLnG8KxNp2fO1/U/ioAz0Rb85in7Ean6JS2J9dzo1nSssm7ZyQvGgc1e7EVtztbVpHThsvw92+/mvlQkRRQ+sp2To8PcSMeEVI+TqBOg6BWbwwNQLzu2Gr14xRiVLnG8KxNp2fO19/eUJq2o4vBfSpsn7GSDIf6C3F9EahRPGCR/z0kw5GZob3Q==
                test
```

And then POSTs:
```
        class: Tenant
        admin:
            class: User
            userType: regular
            password: "{{{ ADMIN_PASS }}}"
            shell: bash  
            preserveAuthKeys: true
```

I believe in this case the auth keys should be same as they were before DO's first run. Does that line up with your expectations?
