### ISSUE TITLE
Ability to configure Static Management-IP

### ISSUE THREAD

**Issue by f5-applebaum** [F5Networks/f5-declarative-onboarding#224]
### Is your feature request related to a problem? Please describe.

In GCP after a NIC SWAP, i need to be able to send a declaration that configures a Management IP as there is no valid DHCP information on that NIC to leverage:

### Describe the solution you'd like
Would like to be able send entire MGMT IP and MGMT Route declaration.

```
          ManagementIp:
            class: ManagementIp
            address: 10.0.0.11/32
          defaultManagementRoute:
            class: ManagementRoute
            mtu: 1460
            network: default
            gw: 10.0.0.1
```

### Describe alternatives you've considered
End up configuring it via tmsh.

### Additional context
Add any other context, such as the desired tmsh configuration, about the feature request here.
