### ISSUE TITLE
add an attribute to name a network object

### ISSUE THREAD

**Issue by vchepkov** [F5Networks/f5-declarative-onboarding#365]
While configuring BigIP manually, it's possible to name object of a different class with the same name,
You can create PUBLIC trunk, PUBLIC vlan and PUBLIC self ip, for example.
It is impossible to do it with declarative onboarding, because yaml requires unique mappings.
if an additional attribute added to the schema, it would be possible to achieve it with something like that:

```
          PUBLIC_VLAN:
            class: VLAN
            title: PUBLIC
          PUBLIC_SELFIP:
            class: SelfIp
            title: PUBLIC
```
